### PR TITLE
Adding installation instruction to Netgear units in Firmwares section

### PR DESCRIPTION
**Pull request by Netduma-Alex**
Added a new page to the FAQ for XR1000 installation instructions, with specific emphasis on the difference between XR1000 and XR1000v2.

### CODE REVIEW

**Comment by Gr3q** [comment]
Is this need to be going to FAQ?

We are trying to get away from the mess that is the FAQ.

**Comment by Netduma-Alex** [comment]
Well where would you put it? I suppose it could go under `Guides > DumaOS 3` but it's intended for a specific unit, to draw attention to the difference between XR1000 and XR1000v2. I think it would look out of place in the Guides section.

**Comment by Gr3q** [comment]
Maybe we need dedicated sections for each of our models? Or maybe this needs to be on the firmware section for that model? Breaking [this](https://support.netduma.com/firmwares/netgear-nighthawk-pro-gaming/) page up to multiple dedicated models with the installation instructions

@rabbled what do you think?

**Comment by Netduma-Alex** [comment]
@Gr3q I have moved the instructions into the Firmwares section as suggested. I added pages for each unit, and linked to those pages from the Netgear index.

**Comment by Netduma-Alex** [comment]
@Gr3q As you'll see, i've flattened the folder structure. Looks much neater.

I did consider changing the titles to just be "NETGEAR XR1000", "NETGEAR XR500" and so on so that they look neater in the sidebar, but I wanted to use the full titles.

Is it possible to have a different title in the sidebar than the actual page it links to?

**Pull request merged**
